### ISSUE TITLE
languageManager using wrong path, prevents text from loading

### ISSUE THREAD

**Issue by sudo-jtcsec** [lucasmartinelle/Bounty-Dashboard#1]
After initial install following the provided directions, my home page would load but no words were rendered. In my apache error logs the following was seen:

PHP Warning:  file_get_contents(/var/www/html/app/languages/EN.json): failed to open stream: No such file or directory in /var/www/html/Bounty-Dashboard/app/languages/languageManager.php on line 10

Inside languageManager.php, the referenced code looks like this:

public function __construct(){
            $this->lang = htmlspecialchars($_COOKIE['lang'], ENT_QUOTES);
            $this->json = json_decode(file_get_contents(WEBSITE_PATH . '/app/languages/'.$this->lang . ".json"));
        }

Changing the third line to the below fixed my problem:

$this->json = json_decode(file_get_contents(WEBSITE_PATH . 'Bounty-Dashboard/app/languages/'.$this->lang . ".json"));

Not sure what the best way is to handle it, but it looks like it wasnt using the proper root path, unless i misconfigured that setting somewhere

**Comment by lucasmartinelle** [comment]
Thank you for your feedback. We have corrected the problem by changing the path to the root of the website.

**Comment by sudo-jtcsec** [comment]
I used the same change to make mine work locally. Looks great! Loving the tool so far!
