### ISSUE TITLE
SQL Error when updating gain from a report

### ISSUE THREAD

**Issue by sudo-jtcsec** [lucasmartinelle/Bounty-Dashboard#2]
Under reports, if you click "gain" and try to update the value, you get a 500 error. Apache error logs look like below:

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''2b923e28-5778-4170-bdb8-bb014978194d' at line 1 in /var/www/html/Bounty-Dashboard/models/Model.php:53\nStack trace:\n#0 /var/www/html/Bounty-Dashboard/models/Model.php(53): PDO->prepare()\n#1 /var/www/html/Bounty-Dashboard/models/reportHandler.php(128): Models\\Model->statement()\n#2 /var/www/html/Bounty-Dashboard/controllers/controllerReports.php(353): Models\\ReportHandler->updateReport()\n#3 /var/www/html/Bounty-Dashboard/controllers/controllerReports.php(52): controllers\\controllerReports->gainReport()\n#4 /var/www/html/Bounty-Dashboard/app/includes/Routing.php(83): controllers\\controllerReports->__construct()\n#5 /var/www/html/Bounty-Dashboard/index.php(35): app\\includes\\Routing->get()\n#6 {main}\n  thrown in /var/www/html/Bounty-Dashboard/models/Model.php on line 53, referer: http://155.138.162.201/dashboard/reports

Looks like there might be an extra apostrophe with the user ID

**Comment by sudo-jtcsec** [comment]
Same issue when updating the status of a report:

Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''2b923e28-5778-4170-bdb8-bb014978194d' at line 1 in /var/www/html/Bounty-Dashboard/models/Model.php:53\nStack trace:\n#0 /var/www/html/Bounty-Dashboard/models/Model.php(53): PDO->prepare()\n#1 /var/www/html/Bounty-Dashboard/models/reportHandler.php(128): Models\\Model->statement()\n#2 /var/www/html/Bounty-Dashboard/controllers/controllerReports.php(129): Models\\ReportHandler->updateReport()\n#3 /var/www/html/Bounty-Dashboard/controllers/controllerReports.php(64): controllers\\controllerReports->postReport()\n#4 /var/www/html/Bounty-Dashboard/controllers/controllerReports.php(40): controllers\\controllerReports->reports()\n#5 /var/www/html/Bounty-Dashboard/app/includes/Routing.php(83): controllers\\controllerReports->__construct()\n#6 /var/www/html/Bounty-Dashboard/index.php(35): app\\includes\\Routing->get()\n#7 in /var/www/html/Bounty-Dashboard/models/Model.php on line 53, referer: http://155.138.162.201/dashboard/reports

**Comment by lucasmartinelle** [comment]
An apostrophe was missing.. Thank you for your feedback on the tool and I hope that your experience with this tool will not be influenced by these mistakes.

**Comment by sudo-jtcsec** [comment]
No worries - happy to help
